repository_type: pipeline

nf_core_version: 3.4.1

lint:
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
  files_exist:
    - CODE_OF_CONDUCT.md

template:
  org: taylorjohnsonm95
  name: taylordgenes-variant-calling
  description: A germline variant calling pipeline
  author: Taylor Lynch
  version: 1.0.0
  force: true
  outdir: .
  skip_features:
    - gpu
  is_nfcore: false
